import { useEffect, useState } from "react";
import { adminRequest, getEducation, getExperience, getProjects, getProfile, getSiteSettings, getSkills, getSocialLinks } from "../services/api";

const sections = ["Overview", "Profile", "Projects", "Skills", "Experience", "Education", "Social Links", "Site Settings"];
const emptyProject = { title: "", slug: "", short_description: "", description: "", image_url: "", github_url: "", live_url: "", technologies: "", featured: false, display_order: 0 };
const emptyProfile = { name: "", headline: "", bio: "", email: "", phone: "", location: "", profile_image_url: "", resume_url: "", availability: "", github_url: "", linkedin_url: "", website_url: "" };
const emptySkill = { name: "", category: "", icon: "", proficiency: 0, display_order: 0 };
const emptyExperience = { company: "", role: "", location: "", start_date: "", end_date: "", current: false, description: "", technologies: "", display_order: 0 };

function AdminDashboard({ onLogout }) {
  const [active, setActive] = useState("Overview");
  const [counts, setCounts] = useState({});
  const [message, setMessage] = useState("");
  const [profile, setProfile] = useState(null);
  const [projects, setProjects] = useState([]);
  const [skills, setSkills] = useState([]);
  const [experience, setExperience] = useState([]);

  const loadData = async () => {
    try {
      const [profileData, projectData, skillData, experienceData, education, socialLinks, settings] = await Promise.all([getProfile(), getProjects(), getSkills(), getExperience(), getEducation(), getSocialLinks(), getSiteSettings()]);
      setProfile(Array.isArray(profileData) ? profileData[0] || null : profileData || null);
      setProjects(projectData || []); setSkills(skillData || []); setExperience(experienceData || []);
      setCounts({ Profile: profileData ? 1 : 0, Projects: projectData?.length || 0, Skills: skillData?.length || 0, Experience: experienceData?.length || 0, Education: education?.length || 0, "Social Links": socialLinks?.length || 0, "Site Settings": settings ? 1 : 0 });
    } catch (err) { setMessage("Could not load portfolio data. Check that the API is running."); }
  };

  useEffect(() => { loadData(); }, []);

  return <div className="admin-shell">
    <aside className="admin-sidebar"><div><div className="admin-brand">AKSHAY<span>.</span></div><p className="admin-sidebar-label">Management</p><nav>{sections.map((section) => <button key={section} className={active === section ? "active" : ""} onClick={() => { setActive(section); setMessage(""); }}>{section}</button>)}</nav></div><button className="admin-logout" onClick={() => { localStorage.removeItem("portfolio_admin_token"); onLogout(); }}>Sign out</button></aside>
    <main className="admin-main"><header className="admin-header"><div><p className="admin-eyebrow">Admin Dashboard</p><h1>{active}</h1></div><a href="/" className="admin-view-site">View portfolio ↗</a></header>{message && <div className="admin-notice">{message}</div>}
      {active === "Overview" ? <Overview counts={counts} onSelect={setActive} /> : active === "Profile" ? <ProfileEditor profile={profile} onSaved={(saved) => { setProfile(saved); setCounts((c) => ({ ...c, Profile: 1 })); }} /> : active === "Projects" ? <ProjectsEditor projects={projects} onChanged={loadData} /> : active === "Skills" ? <SkillsEditor skills={skills} onChanged={loadData} /> : active === "Experience" ? <ExperienceEditor experience={experience} onChanged={loadData} /> : <ResourcePanel section={active} />}
    </main>
  </div>;
}

function Overview({ counts, onSelect }) { return <><div className="admin-welcome"><p className="admin-eyebrow">Control center</p><h2>Keep your portfolio current.</h2><p>Manage the content powering your public portfolio from one place.</p></div><div className="admin-stats">{sections.slice(1).map((section) => <button key={section} onClick={() => onSelect(section)} className="admin-stat-card"><span>{section}</span><strong>{counts[section] ?? "—"}</strong><small>Manage →</small></button>)}</div></>; }

function ProfileEditor({ profile, onSaved }) {
  const [form, setForm] = useState({ ...emptyProfile, ...(profile || {}) }); const [saving, setSaving] = useState(false); const [status, setStatus] = useState("");
  useEffect(() => setForm({ ...emptyProfile, ...(profile || {}) }), [profile]);
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const save = async (event) => { event.preventDefault(); setSaving(true); setStatus(""); try { const data = profile?.id ? await adminRequest(`/profile/${profile.id}`, { method: "PUT", body: JSON.stringify(form) }) : await adminRequest("/profile", { method: "POST", body: JSON.stringify(form) }); const saved = Array.isArray(data) ? data[0] : data; onSaved(saved); setStatus("Profile saved successfully."); } catch (err) { setStatus(err.message || "Failed to save profile."); } finally { setSaving(false); } };
  const fields = [["name", "Name", true], ["headline", "Headline"], ["email", "Email"], ["phone", "Phone"], ["location", "Location"], ["availability", "Availability"], ["profile_image_url", "Profile image URL"], ["resume_url", "Resume URL"], ["github_url", "GitHub URL"], ["linkedin_url", "LinkedIn URL"], ["website_url", "Website URL"]];
  return <form className="admin-editor" onSubmit={save}><div className="admin-form-grid">{fields.map(([key, label, required]) => <label key={key}>{label}<input type={key === "email" ? "email" : "text"} value={form[key] || ""} onChange={(e) => update(key, e.target.value)} required={required} /></label>)}</div><label>Bio<textarea rows="7" value={form.bio || ""} onChange={(e) => update("bio", e.target.value)} /></label>{status && <div className={status.includes("successfully") ? "admin-success" : "admin-error"}>{status}</div>}<div className="admin-editor-actions"><button className="admin-primary-button admin-save-button" disabled={saving}>{saving ? "Saving..." : "Save changes"}</button></div></form>;
}

function ProjectsEditor({ projects, onChanged }) {
  const [editing, setEditing] = useState(null); const [status, setStatus] = useState("");
  const save = async (project) => { setStatus(""); try { const payload = { ...project, technologies: typeof project.technologies === "string" ? project.technologies.split(",").map((v) => v.trim()).filter(Boolean) : project.technologies, display_order: Number(project.display_order) || 0 }; await (project.id ? adminRequest(`/projects/${project.id}`, { method: "PUT", body: JSON.stringify(payload) }) : adminRequest("/projects", { method: "POST", body: JSON.stringify(payload) })); setEditing(null); setStatus(project.id ? "Project updated successfully." : "Project created successfully."); await onChanged(); } catch (err) { setStatus(err.message || "Failed to save project."); } };
  const remove = async (project) => { if (!window.confirm(`Delete “${project.title}”?`)) return; try { await adminRequest(`/projects/${project.id}`, { method: "DELETE" }); setStatus("Project deleted successfully."); await onChanged(); } catch (err) { setStatus(err.message || "Failed to delete project."); } };
  if (editing) return <ProjectForm initial={editing} onCancel={() => setEditing(null)} onSave={save} status={status} />;
  return <section><div className="admin-section-toolbar"><p className="admin-muted">{projects.length} project{projects.length === 1 ? "" : "s"}</p><button className="admin-primary-button admin-add-button" onClick={() => setEditing({ ...emptyProject })}>+ Add project</button></div>{status && <div className="admin-success">{status}</div>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Project</th><th>Featured</th><th>Order</th><th>Actions</th></tr></thead><tbody>{projects.length ? projects.map((project) => <tr key={project.id}><td><strong>{project.title}</strong><small>{project.slug}</small></td><td>{project.featured ? "Yes" : "No"}</td><td>{project.display_order ?? 0}</td><td><button onClick={() => setEditing({ ...project, technologies: Array.isArray(project.technologies) ? project.technologies.join(", ") : project.technologies || "" })}>Edit</button><button className="admin-danger-button" onClick={() => remove(project)}>Delete</button></td></tr>) : <tr><td colSpan="4" className="admin-empty-row">No projects yet. Add your first project.</td></tr>}</tbody></table></div></section>;
}

function ProjectForm({ initial, onCancel, onSave, status }) {
  const [form, setForm] = useState({ ...emptyProject, ...initial }); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <form className="admin-editor" onSubmit={(e) => { e.preventDefault(); onSave(form); }}><div className="admin-form-grid"><label>Title<input value={form.title || ""} onChange={(e) => update("title", e.target.value)} required /></label><label>Slug<input value={form.slug || ""} onChange={(e) => update("slug", e.target.value)} required /></label><label>Short description<input value={form.short_description || ""} onChange={(e) => update("short_description", e.target.value)} /></label><label>Image URL<input value={form.image_url || ""} onChange={(e) => update("image_url", e.target.value)} /></label><label>GitHub URL<input value={form.github_url || ""} onChange={(e) => update("github_url", e.target.value)} /></label><label>Live URL<input value={form.live_url || ""} onChange={(e) => update("live_url", e.target.value)} /></label><label>Technologies<input placeholder="React, Node.js, Supabase" value={form.technologies || ""} onChange={(e) => update("technologies", e.target.value)} /></label><label>Display order<input type="number" value={form.display_order ?? 0} onChange={(e) => update("display_order", e.target.value)} /></label></div><label>Description<textarea rows="8" value={form.description || ""} onChange={(e) => update("description", e.target.value)} /></label><label className="admin-checkbox"><input type="checkbox" checked={Boolean(form.featured)} onChange={(e) => update("featured", e.target.checked)} /> Featured project</label>{status && <div className="admin-error">{status}</div>}<div className="admin-editor-actions"><button type="button" className="admin-secondary-button" onClick={onCancel}>Cancel</button><button className="admin-primary-button admin-save-button">Save project</button></div></form>;
}

function SkillsEditor({ skills, onChanged }) {
  const [editing, setEditing] = useState(null); const [status, setStatus] = useState("");
  const save = async (skill) => { setStatus(""); try { const payload = { ...skill, proficiency: Number(skill.proficiency) || 0, display_order: Number(skill.display_order) || 0 }; await (skill.id ? adminRequest(`/skills/${skill.id}`, { method: "PUT", body: JSON.stringify(payload) }) : adminRequest("/skills", { method: "POST", body: JSON.stringify(payload) })); setEditing(null); setStatus(skill.id ? "Skill updated successfully." : "Skill created successfully."); await onChanged(); } catch (err) { setStatus(err.message || "Failed to save skill."); } };
  const remove = async (skill) => { if (!window.confirm(`Delete “${skill.name}”?`)) return; try { await adminRequest(`/skills/${skill.id}`, { method: "DELETE" }); setStatus("Skill deleted successfully."); await onChanged(); } catch (err) { setStatus(err.message || "Failed to delete skill."); } };
  if (editing) return <SkillForm initial={editing} onCancel={() => setEditing(null)} onSave={save} status={status} />;
  return <section><div className="admin-section-toolbar"><p className="admin-muted">{skills.length} skill{skills.length === 1 ? "" : "s"}</p><button className="admin-primary-button admin-add-button" onClick={() => setEditing({ ...emptySkill })}>+ Add skill</button></div>{status && <div className="admin-success">{status}</div>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Skill</th><th>Category</th><th>Proficiency</th><th>Order</th><th>Actions</th></tr></thead><tbody>{skills.length ? skills.map((skill) => <tr key={skill.id}><td><strong>{skill.name}</strong><small>{skill.icon || "No icon"}</small></td><td>{skill.category}</td><td>{skill.proficiency ?? 0}%</td><td>{skill.display_order ?? 0}</td><td><button onClick={() => setEditing({ ...skill })}>Edit</button><button className="admin-danger-button" onClick={() => remove(skill)}>Delete</button></td></tr>) : <tr><td colSpan="5" className="admin-empty-row">No skills yet. Add your first skill.</td></tr>}</tbody></table></div></section>;
}

function SkillForm({ initial, onCancel, onSave, status }) {
  const [form, setForm] = useState({ ...emptySkill, ...initial }); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <form className="admin-editor" onSubmit={(e) => { e.preventDefault(); onSave(form); }}><div className="admin-form-grid"><label>Name<input value={form.name || ""} onChange={(e) => update("name", e.target.value)} required /></label><label>Category<input value={form.category || ""} onChange={(e) => update("category", e.target.value)} required /></label><label>Icon<input placeholder="react / python / database" value={form.icon || ""} onChange={(e) => update("icon", e.target.value)} /></label><label>Proficiency (%)<input type="number" min="0" max="100" value={form.proficiency ?? 0} onChange={(e) => update("proficiency", e.target.value)} /></label><label>Display order<input type="number" min="0" value={form.display_order ?? 0} onChange={(e) => update("display_order", e.target.value)} /></label></div>{status && <div className="admin-error">{status}</div>}<div className="admin-editor-actions"><button type="button" className="admin-secondary-button" onClick={onCancel}>Cancel</button><button className="admin-primary-button admin-save-button">Save skill</button></div></form>;
}

function ExperienceEditor({ experience, onChanged }) {
  const [editing, setEditing] = useState(null); const [status, setStatus] = useState("");
  const save = async (item) => { setStatus(""); try { const payload = { ...item, technologies: typeof item.technologies === "string" ? item.technologies.split(",").map((v) => v.trim()).filter(Boolean) : item.technologies, display_order: Number(item.display_order) || 0, current: Boolean(item.current) }; await (item.id ? adminRequest(`/experience/${item.id}`, { method: "PUT", body: JSON.stringify(payload) }) : adminRequest("/experience", { method: "POST", body: JSON.stringify(payload) })); setEditing(null); setStatus(item.id ? "Experience updated successfully." : "Experience created successfully."); await onChanged(); } catch (err) { setStatus(err.message || "Failed to save experience."); } };
  const remove = async (item) => { if (!window.confirm(`Delete “${item.role} at ${item.company}”?`)) return; try { await adminRequest(`/experience/${item.id}`, { method: "DELETE" }); setStatus("Experience deleted successfully."); await onChanged(); } catch (err) { setStatus(err.message || "Failed to delete experience."); } };
  if (editing) return <ExperienceForm initial={editing} onCancel={() => setEditing(null)} onSave={save} status={status} />;
  return <section><div className="admin-section-toolbar"><p className="admin-muted">{experience.length} experience entr{experience.length === 1 ? "y" : "ies"}</p><button className="admin-primary-button admin-add-button" onClick={() => setEditing({ ...emptyExperience })}>+ Add experience</button></div>{status && <div className="admin-success">{status}</div>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Role</th><th>Company</th><th>Period</th><th>Order</th><th>Actions</th></tr></thead><tbody>{experience.length ? experience.map((item) => <tr key={item.id}><td><strong>{item.role}</strong><small>{item.location || "Location not set"}</small></td><td>{item.company}</td><td>{item.start_date || "—"} → {item.current ? "Present" : (item.end_date || "—")}</td><td>{item.display_order ?? 0}</td><td><button onClick={() => setEditing({ ...item, technologies: Array.isArray(item.technologies) ? item.technologies.join(", ") : item.technologies || "" })}>Edit</button><button className="admin-danger-button" onClick={() => remove(item)}>Delete</button></td></tr>) : <tr><td colSpan="5" className="admin-empty-row">No experience yet. Add your first role.</td></tr>}</tbody></table></div></section>;
}

function ExperienceForm({ initial, onCancel, onSave, status }) {
  const [form, setForm] = useState({ ...emptyExperience, ...initial }); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <form className="admin-editor" onSubmit={(e) => { e.preventDefault(); onSave(form); }}><div className="admin-form-grid"><label>Company<input value={form.company || ""} onChange={(e) => update("company", e.target.value)} required /></label><label>Role<input value={form.role || ""} onChange={(e) => update("role", e.target.value)} required /></label><label>Location<input value={form.location || ""} onChange={(e) => update("location", e.target.value)} /></label><label>Start date<input type="date" value={form.start_date || ""} onChange={(e) => update("start_date", e.target.value)} /></label><label>End date<input type="date" value={form.end_date || ""} disabled={Boolean(form.current)} onChange={(e) => update("end_date", e.target.value)} /></label><label>Technologies<input placeholder="React, Node.js, PostgreSQL" value={form.technologies || ""} onChange={(e) => update("technologies", e.target.value)} /></label><label>Display order<input type="number" min="0" value={form.display_order ?? 0} onChange={(e) => update("display_order", e.target.value)} /></label></div><label className="admin-checkbox"><input type="checkbox" checked={Boolean(form.current)} onChange={(e) => update("current", e.target.checked)} /> Currently working here</label><label>Description<textarea rows="8" value={form.description || ""} onChange={(e) => update("description", e.target.value)} /></label>{status && <div className="admin-error">{status}</div>}<div className="admin-editor-actions"><button type="button" className="admin-secondary-button" onClick={onCancel}>Cancel</button><button className="admin-primary-button admin-save-button">Save experience</button></div></form>;
}

function ResourcePanel({ section }) { const descriptions = { Education: "Manage education history and ordering.", "Social Links": "Keep your social profiles and external links up to date.", "Site Settings": "Control site metadata, accent color and contact settings." }; return <section className="admin-empty-panel"><div className="admin-panel-icon">{section.charAt(0)}</div><h2>{section}</h2><p>{descriptions[section]}</p><span className="admin-coming-soon">Editor coming next</span></section>; }
export default AdminDashboard;
